version: v1.0
name: Build Workspace Container

agent:
  machine:
    type: e1-standard-8
    os_image: ubuntu1804

blocks:
  - name: "Build and Push"
    task:
      secrets:
        - name: api-keys

      prologue:
        commands:
          - checkout
          - echo "$DOCKER_PASSWORD" | docker login registry.gitlab.com -u "$DOCKER_USERNAME" --password-stdin &> /dev/null
          - docker pull registry.gitlab.com/baalajimaestro/codespace-workspace
      jobs:
      - name: Build
        commands:     
          - DOCKER_BUILDKIT=1 docker build --cache-from registry.gitlab.com/baalajimaestro/codespace-workspace --build-arg BUILDKIT_INLINE_CACHE=1 -t registry.gitlab.com/baalajimaestro/codespace-workspace:latest .
      
      epilogue:
        on_pass:
          commands:
          - docker history registry.gitlab.com/baalajimaestro/codespace-workspace:latest                
          - docker push registry.gitlab.com/baalajimaestro/codespace-workspace:latest